var global_data = {
    TEAMS: [
        {teamAbbr : "DEN", players: []},
        {teamAbbr : "NYJ", players: []},
        {teamAbbr : "TB", players: []},
        {teamAbbr : "SEA", players: []},
        {teamAbbr : "CHI", players: []},
        {teamAbbr : "TEN", players: []},
        {teamAbbr : "GB", players: []},
        {teamAbbr : "ARI", players: []},
        {teamAbbr : "WAS", players: []},
        {teamAbbr : "LAC", players: []},
        {teamAbbr : "HOU", players: []},
        {teamAbbr : "MIN", players: []},
        {teamAbbr : "PIT", players: []},
        {teamAbbr : "STL", players: []},
        {teamAbbr : "MIA", players: []},
        {teamAbbr : "BAL", players: []},
        {teamAbbr : "CAR", players: []},
        {teamAbbr : "NE", players: []},
        {teamAbbr : "DAL", players: []},
        {teamAbbr : "NO", players: []},
        {teamAbbr : "SF", players: []},
        {teamAbbr : "CLE", players: []},
        {teamAbbr : "IND", players: []},
        {teamAbbr : "PHI", players: []},
        {teamAbbr : "JAX", players: []},
        {teamAbbr : "CIN", players: []},
        {teamAbbr : "DET", players: []},
        {teamAbbr : "KC", players: []},
        {teamAbbr : "BUF", players: []},
        {teamAbbr : "ATL", players: []},
        {teamAbbr : "OAK", players: []},
        {teamAbbr : "NYG", players: []},
        {teamAbbr : "LA", players: []}
    ]
}
